Squashed 'extern/fmt/' changes from cd4af11ef..cc09f1a67
cc09f1a67 Update version
e4eb242ce Update changelog and bump version
ce98e0c6a Fix fallback float formatter at assymetric bounds (#1976)
5f7f7b954 Update version
5d3f0741e Update changelog and bump version
563cbb6c2 Add a macro to workaround clang/gcc ABI incompatibility on ARM
425778aa6 Fix ABI compatibility (#1961)
69a84198b Remove accidental parenthesis (#1968)
5c0450493 Removed [-Wsign-conversion] warning in GCC
556a1cfb3 Instantiate to_decimal to make gcc lto happy (#1955)
28a8eae85 Cleanup
236fea1f0 Workaround bugs in gcc 8
4fe0b1119 Update version
df4bd60f4 Bump version
764fb35e1 Always install the required version of breathe
e1bdc0eca Use the correct version of sphinx
39bde329b Tweak markup
204d299ab Tweak markup
e0995b1c1 Update readme
4af178bdf Remove outdated build config
aa41dc02b Remove unused script
6a77ea3c9 Tweak markup
62c72059d Update changelog
c10e3f7f4 Update changelog
e542e6953 Update changelog
530cf316b Point to the release, not dev documentation
740385d63 Update changelog
cd4651116 Update changelog
46291be34 Update changelog
90071c1df Update ChangeLog.rst
25293d7ac Update ChangeLog.rst
5024742f8 Update ChangeLog.rst
0452a4e71 Update changelog
8de96817c Woraround bugs in gcc 8
47e167679 Simplify arg formatter
f0a42346a Move parsing optimization one level up
86287b8d5 Optimize common case in parse_format_specs
8924211f3 Update README.rst
525e7649c Update CONTRIBUTING.md
0ecb3d182 Optimize alignment parsing
975530784 Optimize format_uint
7446818f9 Simplify vformat_to
280b5612c Add option to force usage of inline namespaces
e57ec7d56 Merge vformat_to overloads
2a3f4de3f Remove iterator_category
27fdb4ead Unshadow floaty
297e0bad8 Apply clang-format
e3b4c22ec Simplify is_output_iterator
da8278e1e Update changelog and bump version
17fba753c added position independent documentation (#1939)
71e705a27 Update README.rst
74654c8cb Fix compilation for systems without fcntl.h (#1942)
f468b203a Avoid conversion from long long to size_t (#1935)
20d4f2e83 Fix handling of weird character types when parsing sign (#1932)
08370c39f Update README.rst
bd3c79250 Fix float fuzzer
8d3fd86d6 Merge branch 'master' of github.com:fmtlib/fmt
403471571 Update README.rst
37d738fa6 Update README.rst
271eff149 Make classes derived from buffer<T> final to silence the virtual destructor warning. (#1937)
010efc310 Add float fuzzer and cleanup
811c8b58c Add float fuzzer and cleanup
82c4e2236 Cleanup fuzzing
63e40c961 Fix naming of fuzzers
2f448ed56 Fix fuzzer timeouts
af2830596 Cleanup
48ea8193d Explain why assert-test is a separate test
1d112bdd1 Remove old test
5eb292a65 Update README.rst
7e56b6b6c Fix coding style and remove duplicate fuzzer
41d97e1ef Fix a UB on ridiculously large precision
01c37e0a4 Added check for `-mbig-obj` and ref qualifier check (#1929)
a5e7e7db9 Fix handling of thousand separator (#1927)
bf19051a9 Optimize floating point formatting
3c13a88b1 Optimize floating point formatting
f6d75c534 Refactor write_float
e9c0b2d69 Merge write_float overloads
7eddbfed5 Cleanup exponent handling in write_float
b347b3023 Update dynamic_formatter comment (#1923)
3541880ef Fix integer overflow when using max int precision
7b50dc0b2 Don't exclude all detail symbols from docs
280524310 Fix the doc config
34f22e88a Cleanup CMake config
a18b3fbbd Fix fixed precision handling when rounding (#1917)
727703573 Fix long lines in usage.md
7612c1ea8 Add reference to lhelper package manager in usage
b91d39f20 Get rid of float_writer
b4b64b9cc Refactor float formatting
712abe40f Workaround a bug in gcc 7.5 (#1912)
af8a180ae Make GetCachedPower test more precise
a581e9e5d Fix warning C4018: '<=': signed/unsigned mismatch (#1908)
05a28312c Update docs
4d0aa4d8f Update link
575f40189 Simplify FP formatting and follow coding conventions
6f3536f97 Move zero-check to an earlier branch (#1906)
90ef46df0 Fix dragonbox integration
3ae88147e Fix declaration
641795257 Improve dragonbox integration
79694d424 Fix WriteConsole signature
51f2e2ca2 Move nan test to where it belongs
68555fdbd Make format-test not depend on color.h
63e0c3541 Make dragonbox::to_decimal available in format.h
2213a7110 Update README.rst
79ba37f3b Update README.rst
a905d8f70 Merge grisu-test into format-test
762c33a96 Simplify windows handling (#1903)
253d63159 Remove dependency on windows.h (#1900)
c156093ff Fix carry in fallback_format
34179b335 Update format.h (#1898)
0651e4598 Minor tweaks to get_cached_power
6c025520a Test that max_k is correctly defined
51f8d0cc2 Reuse log10_2_significand constant
1305cbeb6 Fix MSVC2019 error C2049 when compiling with /clr (#1897)
2d4fde3a2 Don't emit trailing zero for consistency with std::format
5fd89d50e Minor simplifications
605ce5e42 Simplify divisible_by_power_of_2
085171e7e Remove grisu_count_digits
aa729bf25 Remove dead code
aa2ddf9b8 Simplify Dragonbox integration
c1654ce48 Simplify uint32_or_64_or_128_t definition
33712dc07 Combine pragmas
e5942ac9d Tweak comments
aae7a1338 Remove unused pragmas
6bcde9aab https://github.com/fmtlib/fmt/pull/1882#issuecomment-696823912 (#1894)
bb0db5e51 clang-format
16410056b Optimize copy_str for counting_iterator
2591ab91c MSVC optimizations for count_digits. (#1890)
d5b8002dc Update README.rst
821471e1d qkw: generalizing aliasing | using fmt library and it's features (#1888)
2e620ddbc Small improvements that should have zero to negligible impact on the runtime (#1887)
2f7e08856 Disable range formatter if value type is not formattable (#1885)
c46a8de4e Simplify test
2696dc927 add forgotten template argument to make_format_args which made some u… (#1877)
0016da7ab Don't generate zeros and fix UB on huge precision
ce3f76994 Merge intrinsic blocks
3b6248f60 Change formatting
2d9b1dd0a Fix sign mismatch
1f0600a23 Fix bug regarding FMT_SAFEBUFFERS
2ecdbb986 Fix a bug in ctzll
6f81ea151 Fix typo (and thus bug)
0c8ffe9b0 Implement Dragonbox (first version)
42699bf40 Fix msvc version of clz & clzll (#1880)
bc51a8df0 Disable fallthrough attributes for the Intel compilers on Linux and MacOS (#1879)
45da432d6 fix compiler warnings in public header files
d55e61f12 Improve FMT_ALWAYS_INLINE (#1878)
7e6827521 Remove trailing zeros when using fallback formatter (#1873)
1d696dc28 Handle exotic character types in compilation
f674434a6 Add format_to_n overload that accepts FMT_COMPILE (from #1767) (#1869)
5b5a59719 Fix handling of wide alignment
f80ed64dd Update README.rst
381396649 Simplify fallback format
dce8e49b4 Handle float in fallback formatter
78b594431 Spelling
f233b56cd Don't generate insignificant digits
595902f8a Update test
4f2ee8921 Use built-in FP formatter for any precision
58a044be5 Use built-in FP formatter for any precision
efe3694f1 Macro tweak and clang-format
9f312fe87 Implement fallback FP formatting with given precision (#1526)
fb289cf56 Fix coding conventions
86f0a7046 Fix formatting
bff4d18ef Add color format_to overloads * Fix variable size basic_memory_buffer colorization * Fix an unused arguments warning on GCC that blocks the CI otherwise * Ref #1842 * Ref #1593
f19b8885f Fixed a warning in mingw32/mingw64 (#1860)
f8e00a084 NOMINMAX not handled properly (#1855)
6cccdc24b Fix move constructor (#1844)
69902c178 Allow use of <fcntl.h> in Linux when __has_include is not available (#1848)
1edd38b96 Add append mode. (#1847)
e66ba1692 Added build2 usage instructions. (#1838)
f39e6fb61 Add formatters for chrono::time_point<system_clock> (#1837)
77b627be2 Fix bogus MSVC warnings (#1825)
5dff01d31 Add complex tests
d16d585e6 Update signatures
c7e6d8afb Fix usage of override (#1836)
92bff2fe2 Revert "Add missing includes"
a0dcfbc57 Add ptr to docs
1651b2d43 Fix detail::write with fallback formatter (#1829)
06895a768 Add missing includes
92a448a07 Apply clang-format
6be654466 Fixing buffer_appender's ++ slicing (#1822)
951e0d233 CMakeLists.txt: Added Wundef warning to clang and gcc. (#1823)
f9f02df71 CMakeLists.txt: Clang-warnings: removed -Wno-sign-conversion (#1817)
76e97dc4d Eliminate shadowed variable warnings on intel (#1816)
e204df0e6 nvcc compiler should be EDG-based, but fails test (#1818)
1c8bb5470 small changes to reduce clang-9 warnings (#1808)
4b69c7875 fix: warning C4100: unreferenced formal parameter (#1814)
fb0aeb820 fix: disabled UDL templates for PGI (#1811) (#1812)
54daa0864 Add dynamic width support to FMT_COMPILE (#1809)
6fb7c6fb2 Workaround a bug in gcc10 (#1810)
16985fdad Update README.rst
1378ddaef Update README.rst
4fd95e4b4 Don't remove trailing zeros with #
e06ae3229 Avoid warnings on functions with external linkage that don't have declarations
7fc3d1f54 Add override to grow
065889a59 Use correct capacity in iterator_buffer (#1807)
d0dd67869 Adding convenience append(range)
0e7cef069 Merge commit 'c13f79e0'
e2c8c4557 Update README.rst
e4c954ff0 Update README.rst
c13f79e09 Merge release branch
d7921d649 Update README.rst
4a4fc225e Update changelog
61602a75d Remove -Wno-shadow
2f8fc29e9 Update README.rst
717b226b5 include/fmt/format.h: explicit cast to std::size_t for parameter to buffer.resize() in order to get rid of warning 'implicit conversion changes signedness:' in clang-8 (#1802)
2a69f5676 Tweak buffer size
ea7693380 Simplify ostream
5413713c9 Remove unused function
57f462428 Increase the default buffer size
0b6e7cc60 Update README.rst
e587adb4e Simplify count_digits
279d698e1 Fix handling of default alignmment with locale (#1801)
76cfb50b2 Test complex formatter
208291205 Optimize count_digits
8d9ab9673 Cut a few cycles from count_digits
734344931 Simplify ostream_params
2a47a1e48 Update README.rst
7c4c5c79d Make buffer size configurable
f0b84da5f Don't use 128 bit integers with clang-cl (#1800)
a3dfd6f92 Workaround a bug in msvc
51d05521e Workaround broken numeric_limites, part 2 (#1787)
21c8b5c14 Report error on missing named argument (#1796)
d82fdcc9e Fix handling of iterators in locale-specific formatting (#1782)
633213d96 Merge release branch
e8f2580a4 Bump version
6cefe55ac Update changelog
64e2da15c Update README.rst
1c8c810f8 Update README.rst
c2399ccfc Update README.rst
a7c5db06d Update README.rst
a4c22acd0 Update README.rst
0c1f4b5a0 Update README.rst
63b422ee5 Update README.rst
26e81a673 Update README.rst
de5fc6af3 Update README.rst
9c2edfd1a Partially revert 638db5 because it breaks the doc build
810357c01 Document color
0a7032a40 Update README.rst
95d3abf95 Make format_to_n part of the core API
98626093d Correct the locale format specifier in api.rst (#1792)
47f8d7a34 Make formatted_size part of the core API
46a63b708 Update docs
430f393d6 Disabled __attribute__((deprecated)) usage for LCC (#1790)
febffa4e6 Make join() handle non-const-only begin/end ranges (#1786)
d69e2da22 Fix apidoc
ce73ea37f Reorder functions
d39d661b1 Workaround broken numeric_limits (#1725)
c228bfe88 Improve docs
38ce19f73 Update README.rst
d11849bc0 Add FMT_REDUCE_INT_INSTANTIATIONS flag (#1781)
c08518a25 Move make_args_checked to the public API
e2837084e Add a color section
9f0c00337 Simplify format string checks
d615137ca Improve handling of buffer iterator
26b47b6fb Bump tested CMake version to 3.18
7a01c9c52 Update README.rst
b17d5c4f5 Fix a regression in handling digit separators (#1782)
eb90da2e8 Type erase output iterators
9d3cd0afb Type erase output iterators
18024853b Fix compatibility with CMake 3.4 (#1779)
f5d4215b7 Trying to clear ambiguous compile time claims (#1775)
c26349f4d Improve error reporting
f4b11ef6e Add a short anchor
0097cf113 Report unformattable type name more prominently
8fa20b471 dev -> latest
a03bd3ddb Autodetect MSVC static runtime (#1770)
c108ee1d5 Clarify a comment
a8074a865 Update README.rst
5f6295486 Update README.rst
bd903f96a Clarify precedence
16cac46a0 Improve handling of streamable and convertible to bool types (#1766)
415cd5191 direct_buffered_file -> ostream
e1bfb5961 Fix handling of code units in compile
ba8d98cbb Cleanup direct_buffered_file
04a1f6e99 Improve handling of single code units in compile
e4f57bfd7 Add an overload of write for buffer_appender
d87046815 Make append work with fixed-size buffer
e8ec09ae8 Cleanup core-test
a2c4fed98 Double buffering no more
36406509d Add a fixed buffer
60c43e870 Apply clang-format
b998e0f30 Reduce symbol sizes and simplify iterator use
c5adfc51c Update README.rst
c4ad94ce2 Update README.rst
c1429651e Fix image source link
638db5ca5 Use Cmake to find Python and Sphinx-doc.
c09056975 Update readme
1efdb2dde Simplify readme
dc69afad1 Cleanup example
445f5d392 Break long lines
23063c344 Update readme
f57b62575 Move PR template to the top level

git-subtree-dir: extern/fmt
git-subtree-split: cc09f1a6798c085c325569ef466bcdcffdc266d4